#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: zhengmz
#=================================================

name: Sync Code

on: 
  #schedule:
  #  - cron: 10 16 1 * *
  # every month second day 0:10 CST
  #  - cron: 10 16 * * *
  # every day
  #  - cron: 10 16 * * 0
  # every Sunday 16:10 UTC, as Monday 0:10 CST
  #  - cron: 10 16 1 1,4,7,10 *
  # every quarter second day 0:10 CST
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      sync_code:
        description: 'Sync code'
        type: boolean
        required: true
        default: 'true'
      create_release:
        description: 'Create release'
        type: boolean
        required: true
        default: 'false'
      delete_release:
        description: 'Delete older release'
        type: boolean
        required: true
        default: 'false'
      delete_run:
        description: 'Delete older workflow run'
        type: boolean
        required: true
        default: 'true'

env:
  SYNC_CODE: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.sync_code || 'true' }}
  CREATE_RELEASE: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.create_release || 'true' }}
  DELETE_OLD_RELEASE: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.delete_release || 'true' }}
  DELETE_OLD_RUN: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.delete_run || 'true' }}

jobs:
  sync:
    runs-on: ubuntu-latest

    # For create release
    permissions:
      contents: write

    if: github.event.repository.owner.id == github.event.sender.id

    strategy:
      #max-parallel: 1
      fail-fast: false
      matrix:
        model: 
          - repo
          - dir

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Get system infomation
      run: |
        #set +e
        echo "CPU: $(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c)"
        echo "UserName: $(whoami)"
        echo -e "SystemInfo: \n$(lsb_release  -a 2>&1 | grep -vi 'No LSB')\n"
        echo -e "Disk space: \n$(df -h)\n"
        echo -e "Environment: \n$(env)\n"
        echo "Github object json:"
        cat << EOF
          ${{ toJson(github) }}
        EOF

    - name: Sync code from upstream
      if: env.SYNC_CODE == 'true'
      run: |
        set +e
        chmod +x ./sync_code.sh
        ./sync_code.sh "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"

    - name: Add environment variables
      env:
        TZ: 'Asia/Shanghai'
        DEVICE_NAME: 'Sync_Code_${{ matrix.model }}'
      run: |
        echo "BUILD_TIME=$(date '+%F %T %Z')" >> $GITHUB_ENV
        BUILD_DATE="$(date '+%Y%m%d')"
        echo "DEVICE_NAME=${DEVICE_NAME}" >> $GITHUB_ENV
        TAG_NAME="${DEVICE_NAME}"
        echo "TAG_NAME=${TAG_NAME}-${BUILD_DATE}" >> $GITHUB_ENV

        # check
        echo "cat GITHUB_ENV ..."
        cat $GITHUB_ENV

    - name: Create release
      uses: ncipollo/release-action@v1
      if: env.CREATE_RELEASE == 'true'
      with:
        name: Sync Code ${{ matrix.model }} ${{ env.BUILD_TIME }}
        allowUpdates: true
        tag: ${{ env.TAG_NAME }}
        commit: master
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          Sync Code ${{ matrix.model }}

    - name: Delete older releases
      #uses: dev-drprasad/delete-older-releases@v0.2.0
      uses: zhengmz/delete-older-releases@v0.2.1
      if: env.DELETE_OLD_RELEASE == 'true'
      with:
        keep_latest: 3
        delete_tags: true
        delete_tag_pattern: ${{ env.DEVICE_NAME }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete older workflow runs
      #uses: Mattraks/delete-workflow-runs@v2
      uses: zhengmz/delete-workflow-runs@v2.0.2
      if: env.DELETE_OLD_RUN == 'true'
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 30
        keep_minimum_runs: 3
        delete_workflow_pattern: ${{ github.workflow }}

